[project]
name = "skyvern-research"
version = "0.1.0"
requires-python = "~=3.12.0"
dependencies = [
    "httpx>=0.28.1",
    "skyvern",
]

[tool.uv.sources]
skyvern = { path = "skyvern", editable = true }
